name: LMSParEst
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - tqdm 
  - bokeh
  - matplotlib=3.5.1
  - plotly
  - colorcet
  - jupyter
  - sympy
  - pip
  - pip:
    - neptune
    - torch #==1.9.0
    - torchaudio
    - fbm
    - transformers
    - antropy
    - hurst
    - pathos
    - yfinance
    - cvxpy
    - whittlehurst==0.7
    - dcor
    - minepy